In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False
plt.style.use('seaborn')
plt.rcParams['figure.figsize'] = [8, 4.5]
plt.rcParams['figure.dpi'] = 300

# 텐서 씨드 고정
import tensorflow as tf
import random
import os
#글로벌 시드
class config:
    seed = 1234
    device = "cuda:0"    

def seed_everything(seed: int = 1234):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    tf.random.set_seed(seed)
    
seed_everything(config.seed)

import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

seed =1234

pd.set_option('display.max_rows', 10, 'display.max_columns', 500, 'max_colwidth', None)

In [2]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import KFold
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import seaborn as sns 

import sklearn
from sklearn.linear_model import ElasticNet, LinearRegression
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier, KerasRegressor
np.random.seed(1338)
cmap_data = plt.cm.Paired
cmap_cv = plt.cm.coolwarm
n_splits = 5

import pandas as pd
from pandas_datareader import data as web
import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.model_selection import TimeSeriesSplit

In [4]:
# df = pd.read_csv('./kospi.csv')
df = pd.read_csv('./baseline_hv.csv')

df.shape

(4598, 55)

In [5]:
df.head()

,date,baseline,HV,HV_pred,HV_resid,sum_word,MA5,MA20,MA60,MA120,MA5_gra,MA20_gra,MA60_gra,MA120_gra,V_MA5,V_MA20,V_MA60,V_MA120,EMA5,EMA20,EMA60,EMA120,MACD,MACD_sig9,MACD_OSC,Fast%K,Fast%D,Slow%K,Slow%D,RSI14,RSI signal,CCI,A_Ratio,B_Ratio,ATR,UpDI,DownDI,MFI,Momentum,Sonar,Sonar_sig5,STDEV,Sigma,TRIX,VR,WILLR,Psy,Disparity20,Disparity60,ADX,ADOSC,Volume_OSC,upperband,middleband,lowerband
0,2003-07-28,100.0,NaN,0.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2003-07-29,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.750,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2003-07-30,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2003-07-31,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2003-08-01,100.0,0.0,0.0,0.0,3.0,41.088806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.291079e+07,0.0,0.0,0.0,41.088806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.isnull().sum()

date           0
baseline       0
HV             1
HV_pred       20
HV_resid      21
              ..
ADOSC          0
Volume_OSC     0
upperband      0
middleband     0
lowerband      0
Length: 55, dtype: int64

In [7]:
df['sum_word'].fillna(0,  inplace=True)

In [8]:
df.isnull().sum()

date           0
baseline       0
HV             1
HV_pred       20
HV_resid      21
              ..
ADOSC          0
Volume_OSC     0
upperband      0
middleband     0
lowerband      0
Length: 55, dtype: int64

In [9]:
df.head()

,date,baseline,HV,HV_pred,HV_resid,sum_word,MA5,MA20,MA60,MA120,MA5_gra,MA20_gra,MA60_gra,MA120_gra,V_MA5,V_MA20,V_MA60,V_MA120,EMA5,EMA20,EMA60,EMA120,MACD,MACD_sig9,MACD_OSC,Fast%K,Fast%D,Slow%K,Slow%D,RSI14,RSI signal,CCI,A_Ratio,B_Ratio,ATR,UpDI,DownDI,MFI,Momentum,Sonar,Sonar_sig5,STDEV,Sigma,TRIX,VR,WILLR,Psy,Disparity20,Disparity60,ADX,ADOSC,Volume_OSC,upperband,middleband,lowerband
0,2003-07-28,100.0,NaN,0.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2003-07-29,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.750,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2003-07-30,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2003-07-31,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2003-08-01,100.0,0.0,0.0,0.0,3.0,41.088806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.291079e+07,0.0,0.0,0.0,41.088806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df.set_index('date', inplace=True)

In [11]:
df.head()

,baseline,HV,HV_pred,HV_resid,sum_word,MA5,MA20,MA60,MA120,MA5_gra,MA20_gra,MA60_gra,MA120_gra,V_MA5,V_MA20,V_MA60,V_MA120,EMA5,EMA20,EMA60,EMA120,MACD,MACD_sig9,MACD_OSC,Fast%K,Fast%D,Slow%K,Slow%D,RSI14,RSI signal,CCI,A_Ratio,B_Ratio,ATR,UpDI,DownDI,MFI,Momentum,Sonar,Sonar_sig5,STDEV,Sigma,TRIX,VR,WILLR,Psy,Disparity20,Disparity60,ADX,ADOSC,Volume_OSC,upperband,middleband,lowerband
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2003-07-28,100.0,NaN,0.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-07-29,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.750,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-07-30,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-07-31,100.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-08-01,100.0,0.0,0.0,0.0,3.0,41.088806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.291079e+07,0.0,0.0,0.0,41.088806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df.shape

(4598, 54)

In [13]:
cols = ['HV', 'sum_word','MA5_gra','Volume_OSC','Sigma','Disparity20']#, 'MACD_OSC', 'Sonar', 'Sigma', 'Momentum', 'Volume_OSC',  'ATR','RSI signal','RSI14',  'ADOSC']
cols

['HV', 'sum_word', 'MA5_gra', 'Volume_OSC', 'Sigma', 'Disparity20']

In [14]:
df = df[cols]

In [15]:
df.index

Index(['2003-07-28', '2003-07-29', '2003-07-30', '2003-07-31', '2003-08-01',
       '2003-08-04', '2003-08-05', '2003-08-06', '2003-08-07', '2003-08-08',
       ...
       '2021-10-15', '2021-10-18', '2021-10-19', '2021-10-20', '2021-10-21',
       '2021-10-22', '2021-10-25', '2021-10-26', '2021-10-27', '2021-10-28'],
      dtype='object', name='date', length=4598)

In [16]:
df.head()

             HV  sum_word  MA5_gra  Volume_OSC  Sigma  Disparity20
date
2003-07-28  NaN       0.0      0.0         0.0    0.0          0.0
2003-07-29  0.0       0.0      0.0         0.0    0.0          0.0
2003-07-30  0.0       0.0      0.0         0.0    0.0          0.0
2003-07-31  0.0       0.0      0.0         0.0    0.0          0.0
2003-08-01  0.0       3.0      0.0         0.0    0.0          0.0

In [17]:
df.shape

(4598, 6)

In [18]:
feature_df = df.loc['2003-09-29':'2021-10-28', 'HV':'Disparity20']
print(feature_df.shape)
feature_df.head()

(4554, 6)

                  HV  sum_word   MA5_gra  Volume_OSC     Sigma  Disparity20
date
2003-09-29  0.000000       0.0 -0.003142    0.484744 -1.225259    97.591753
2003-09-30  0.046147       0.0 -0.007730    4.466314 -1.742624    96.506024
2003-10-01  0.111621       0.0  0.002179    8.823151 -0.226977    99.353199
2003-10-02  0.113955       0.0  0.005389    8.880720  0.099223   100.166147
2003-10-03  0.127419       0.0  0.009944    9.854309  0.955635   101.891182

In [19]:
label_df = df.loc['2003-09-29':'2021-10-28', 'HV']
print(label_df.shape)
label_df.head()

(4554,)

date
2003-09-29    0.000000
2003-09-30    0.046147
2003-10-01    0.111621
2003-10-02    0.113955
2003-10-03    0.127419
Name: HV, dtype: float64

# TRAIN, TEST 분리
- 1차 : 2003 ~ 2011 학습 / 2012 ~ 2016 예측
- 2차 : 2003 ~ 2016 학습 / 2017~ 2021 예측

## 1차 train_test 분리

In [20]:
X_train_1st = feature_df.loc['2003-09-29':'2011-09-28']
print(X_train_1st.shape)
X_train_1st.head()

(2016, 6)

                  HV  sum_word   MA5_gra  Volume_OSC     Sigma  Disparity20
date
2003-09-29  0.000000       0.0 -0.003142    0.484744 -1.225259    97.591753
2003-09-30  0.046147       0.0 -0.007730    4.466314 -1.742624    96.506024
2003-10-01  0.111621       0.0  0.002179    8.823151 -0.226977    99.353199
2003-10-02  0.113955       0.0  0.005389    8.880720  0.099223   100.166147
2003-10-03  0.127419       0.0  0.009944    9.854309  0.955635   101.891182

In [21]:
y_train_1st = label_df.loc['2003-09-29':'2011-09-28']
print(y_train_1st.shape)
y_train_1st.head()

(2016,)

date
2003-09-29    0.000000
2003-09-30    0.046147
2003-10-01    0.111621
2003-10-02    0.113955
2003-10-03    0.127419
Name: HV, dtype: float64

### test

In [22]:
X_test_1st = feature_df.loc['2011-09-29':'2021-10-28']
print(X_test_1st.shape)
X_test_1st.head()

(2538, 6)

                  HV  sum_word   MA5_gra  Volume_OSC     Sigma  Disparity20
date
2011-09-29  0.311156      24.0  0.007127    7.613165 -0.607309    97.759248
2011-09-30  0.324805      12.0 -0.001436    6.637214 -1.508087    95.174749
2011-10-03  0.327470      10.5 -0.010362    7.614666 -2.099935    92.930028
2011-10-04  0.340938      42.0 -0.010086   13.034524 -1.284014    95.421343
2011-10-05  0.327492      21.0 -0.002000   12.029998 -0.667012    97.453557

In [23]:
y_test_1st = label_df.loc['2011-09-29':'2021-10-28']
print(y_test_1st.shape)
y_test_1st.head()

(2538,)

date
2011-09-29    0.311156
2011-09-30    0.324805
2011-10-03    0.327470
2011-10-04    0.340938
2011-10-05    0.327492
Name: HV, dtype: float64

In [24]:
print(X_train_1st.shape, y_train_1st.shape)
print(X_test_1st.shape, y_test_1st.shape)

(2016, 6) (2016,)
(2538, 6) (2538,)

## scaling
X와 y를 각각 scaling 해주어야한다.

In [25]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# Standardization 평균 0 / 분산 1
X_scaler = MinMaxScaler()

# 교차검증시
X_scaler.fit(X_train_1st)
X_train_1st_sc = X_scaler.transform(X_train_1st)
X_test_1st_sc = X_scaler.transform(X_test_1st)

In [26]:
# from sklearn.preprocessing import StandardScaler

# Standardization 평균 0 / 분산 1
y_scaler = MinMaxScaler()   

# 교차검증시
y_scaler.fit(np.array(y_train_1st).reshape(-1,1))
y_train_1st_sc = y_scaler.transform(np.array(y_train_1st).reshape(-1,1))
y_test_1st_sc = y_scaler.transform(np.array(y_test_1st).reshape(-1,1))

In [27]:
X_train_1st_sc.shape, X_test_1st_sc.shape, y_train_1st.shape, y_test_1st.shape

((2016, 6), (2538, 6), (2016,), (2538,))

In [28]:
y_train_1st_sc[:5]

array([[0.        ],
       [0.04309432],
       [0.1042375 ],
       [0.10641735],
       [0.11899137]])

In [29]:
y_test_1st_sc[:5]

array([[0.29057482],
       [0.30332099],
       [0.30580974],
       [0.31838696],
       [0.30583013]])

In [30]:
y_train_1st[:5]

date
2003-09-29    0.000000
2003-09-30    0.046147
2003-10-01    0.111621
2003-10-02    0.113955
2003-10-03    0.127419
Name: HV, dtype: float64

In [31]:
y_test_1st[:5]

date
2011-09-29    0.311156
2011-09-30    0.324805
2011-10-03    0.327470
2011-10-04    0.340938
2011-10-05    0.327492
Name: HV, dtype: float64

In [32]:
# 입력 파라미터 feature, label -> numpy type
def make_sequence_dataset(feature, label, window_size):
    feature_list = [] # 생성될 feature list
    label_list = []  # 생성될 label list
    
    for i in range(len(feature)-window_size):
        feature_list.append(feature[i:i+window_size])
        label_list.append(label[i+window_size])
    return np.array(feature_list), np.array(label_list) # 3차원으로 만들어줌

In [33]:
window_size = 20
X_train_1st, y_train_1st = make_sequence_dataset(X_train_1st_sc, y_train_1st_sc, window_size)
X_test_1st, y_test_1st = make_sequence_dataset(X_test_1st_sc, y_test_1st_sc, window_size)
print(X_train_1st.shape, y_train_1st.shape, X_test_1st.shape, y_test_1st.shape) # (batch size, time steps, input dims)

(1996, 20, 6) (1996, 1) (2518, 20, 6) (2518, 1)

# TRAIN, TEST 분리

In [34]:
# input_shape
X_train_1st[0].shape

(20, 6)

# Model

In [35]:
#케라스 모델을 사이킷런 추정기처럼 보이도록 바꿈
def build_model(n_hidden=1, n_neurons=30, learning_rate=0.01, input_shape=[8]):
    model = Sequential()
    model.add(LSTM(n_neurons, activation = 'relu', return_sequences = True, input_shape = X_train_1st[0].shape))
#     model.add(Dropout(0.1))
    
    for layer in range(n_hidden):
        model.add(LSTM(n_neurons, activation = 'relu', return_sequences = True))
#         model.add(Dropout(0.1))
    model.add(Dense(1))
    model.summary()
    
#     optimizer = optimizers.SGD(lr= learning_rate)
    model.compile(loss = 'mse', optimizer = 'adam')
    early_stop = EarlyStopping(monitor = 'val_loss', patience = 15, min_delta=0.001, mode="min", verbose=1)
    history = model.fit(X_train_1st, y_train_1st, validation_data = (X_test_1st, y_test_1st), epochs=50, 
          batch_size=15, callbacks = [early_stop])
    return model

In [36]:
from sklearn.metrics import make_scorer
def rmse(actual, predict):
    predict = np.array(predict)
    actual = np.array(actual)
    distance = predict - actual
    square_distance = distance ** 2
    mean_square_distance = square_distance.mean()
    score = np.sqrt(mean_square_distance)
    return score
rmse_score = make_scorer(rmse, greater_is_better = False)

In [37]:
from sklearn.model_selection import GridSearchCV
keras_reg = KerasRegressor(build_model)
#파라미터 탐색
param_search = {"n_hidden": [1,2,3,4], "n_neurons":[16, 32, 64]} #reciprocal: continuous random variables
# "learning_rate": reciprocal(3e-4, 3e-2)

tscv = TimeSeriesSplit(n_splits=3, test_size= 252)
gsearch = GridSearchCV(estimator=keras_reg, cv=tscv, param_grid=param_search, scoring = rmse_score)

early_stop = EarlyStopping(monitor = 'val_loss', patience = 15)
gsearch.fit(X_train_1st, y_train_1st, epochs = 50, batch_size=15, callbacks = [early_stop])

TypeError: __init__() got an unexpected keyword argument 'test_size'

In [ ]:
best_score = gsearch.best_score_
best_params = gsearch.best_params_

In [ ]:
print('best_score : ', best_score,  '\nbest_params : ', best_params)